<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_BTNPropertyWeb</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3ac9b4ac-d9cf-4b33-a9bf-75d2698ca859</testSuiteGuid>
   <testCaseLink>
      <guid>76222728-a2f6-4ff5-9526-e147209b73cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/calculateNegativeInputedPropertyPrice-TC-4</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6824b13-8994-4092-aeee-c8a9fb2f604c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>489438cc-f360-40dc-b71f-fae0725d2d52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>940aab03-9e8b-438a-92b0-c333a0d7e391</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6980783c-207f-47df-b092-577f0304dd9d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/disabledCalculate-TC3</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b250dbe-10cf-4d5f-aace-abc40c829ec8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39f8997e-73ec-45d5-81c8-708d64f66df5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66158efe-e33a-4215-8b1c-16c662567657</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>30c257a9-3318-49ec-bff1-2ae2ba8b52ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/negative-TC</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b628f4f8-1fa3-4acb-b6f0-58c9bcc981a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f84b28a-bd22-4b25-8d50-85039f95f69f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d3879d6-3cbc-40c7-804f-5ff32dc7b97f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ac18cc5-5fea-4eb5-8a71-fb2e780d91a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/recalculatePropertyPrice-TC2</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad7aa08c-cc4b-4e31-a085-a30a4d9be39b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3e3618f-23dc-40c8-af8b-679abcde0204</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd279b4f-aae0-490e-a1f3-7d05a2b869ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d68c7682-6646-4503-8d6b-d8fdfdb49c7a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e32bdab9-402d-4113-8416-e2bcaf221032</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/verifyCalculatePropertyiPrice-TC5</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>214b1805-20e0-4545-8c8b-86759ebc7318</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>713a44fc-7d4e-4885-a073-a3fddbef5552</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2e9e3fb-ed1f-40f3-8979-2f948acc1fde</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ef5a31d9-e7ff-467d-95a5-b1ace05cea16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/calculatePropertyiPrice-TC1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed1fad3d-db30-4b02-b8ff-6873bf474a8a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ad93e74-ff17-4cd5-a748-8b5545d41c50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d0c2e78-7e8c-4988-8ec1-df621289f930</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
